# Site settings
title: IxDA São Paulo
email: your-email@domain.com
description: "Site do capítulo São Paulo da Interaction Design Association."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "/" # the base hostname & protocol for your site
twitter_username: ixdasp
github_username:  ixda-sao

# Build settings
markdown: kramdown
